services:
  cassandra:
    container_name: temporal-cassandra
    image: cassandra:latest
    ports:
      - 9042:9042

  elasticsearch:
    container_name: temporal-elasticsearch
    environment:
      - cluster.routing.allocation.disk.threshold_enabled=true
      - cluster.routing.allocation.disk.watermark.low=512mb
      - cluster.routing.allocation.disk.watermark.high=256mb
      - cluster.routing.allocation.disk.watermark.flood_stage=128mb
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms256m -Xmx256m
      - xpack.security.enabled=false
    image: elasticsearch:7.17.24
    ports:
      - 9200:9200
    volumes:
      - /var/lib/elasticsearch/data

  temporal:
    container_name: temporal
    depends_on:
      - cassandra
      - elasticsearch
    environment:
      - CASSANDRA_SEEDS=cassandra
      - ENABLE_ES=true
      - ES_SEEDS=elasticsearch
      - ES_VERSION=v7
      - DYNAMIC_CONFIG_FILE_PATH=/etc/temporal/config/dynamicconfig/development-cass.yaml
    image: temporalio/auto-setup:latest
    ports:
      - 7233:7233
    volumes:
      - ./deployment/temporal-dev.yml:/etc/temporal/config/dynamicconfig/development-cass.yaml

  temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:latest
    ports:
      - 8080:8080
